site_name: Epigenome Switchboard
site_logo: img/epigenome_switchboard_logo_dark.svg
site_url: http://code.databio.org/episb/

repo_url: http://github.com/databio/episb-hub
# edit_uri: edit/master/episb-docs/docs/

nav:
  - Getting started:
    - Introducing episb: README.md
  - How-to guides:
    - Query existing data providers: howto-query-provider.md
    - Add a new provider to a hub: howto-subscribe.md
    - Normalize to a segmentation: howto-normalize.md
    - Build a data provider: howto-build-provider.md
    - Build a hub: howto-build-hub.md
  - Reference:
    - Data provider API: provider-api.md
    - Hub API: hub-api.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md

#theme: readthedocs

theme: databio

copyright: Sheffield lab of computational biology

navbar:
  left:
  - text: Episb web app
    icon: fa-play
    href: http://episb.org
  # - text: Documentation
  #   icon: fa-pencil
  #   href: reference/index.html
  - text: GitHub
    icon: fa-github fa-lg
    href: https://github.com/databio/episb-hub
  right:
  - text: Databio.org
    href: http://databio.org
  - text: Software & Data
    href: http://databio.org/software/